{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/google_api_core-1.16.0-py3.8-nspkg.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 1280, in find_spec\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 1252, in _get_spec\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 1383, in find_spec\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 95, in _path_isfile\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 87, in _path_is_mode_type\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 81, in _path_stat\n",
      "  RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "\n",
      "Remainder of file ignored\n",
      "Collecting clean-text\n",
      "  Downloading clean_text-0.2.1-py3-none-any.whl (9.1 kB)\n",
      "Collecting ftfy<6.0,>=5.8\n",
      "  Downloading ftfy-5.8.tar.gz (64 kB)\n",
      "\u001b[K     |████████████████████████████████| 64 kB 5.3 MB/s  eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: wcwidth in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from ftfy<6.0,>=5.8->clean-text) (0.1.7)\n",
      "Building wheels for collected packages: ftfy\n",
      "  Building wheel for ftfy (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for ftfy: filename=ftfy-5.8-py3-none-any.whl size=45612 sha256=7d8a46828887a98a54e2934ef74e88b5e2469c5f3a5f648bad83e4e885fdd3dc\n",
      "  Stored in directory: /Users/patsnap/Library/Caches/pip/wheels/49/1c/fc/8b19700f939810cd8fd9495ae34934b246279791288eda1c31\n",
      "Successfully built ftfy\n",
      "Installing collected packages: ftfy, clean-text\n",
      "  Attempting uninstall: ftfy\n",
      "    Found existing installation: ftfy 5.7\n",
      "    Uninstalling ftfy-5.7:\n",
      "      Successfully uninstalled ftfy-5.7\n",
      "\u001b[31mERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.\n",
      "\n",
      "We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.\n",
      "\n",
      "spacy-transformers 0.5.1 requires spacy<2.3.0,>=2.2.1, but you'll have spacy 2.3.1 which is incompatible.\n",
      "spacy-transformers 0.5.1 requires transformers<2.1.0,>=2.0.0, but you'll have transformers 2.11.0 which is incompatible.\u001b[0m\n",
      "Successfully installed clean-text-0.2.1 ftfy-5.8\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: You are using pip version 20.2; however, version 20.2.1 is available.\r\n",
      "You should consider upgrading via the '/Users/patsnap/anaconda2/bin/python -m pip install --upgrade pip' command.\u001b[0m\r\n"
     ]
    }
   ],
   "source": [
    "!pip install clean-text"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from cleantext import clean"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'i learned everything i know from <url> and <url> and mom.i can be reached at <email> through next friday.i can be reached at <phone> through next friday.i owe <cur>1,000.99 to 123 people for 2+1 reasons.<cur>1.00 equals <cur>0.67 equals <cur>0.91.'"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "clean(\"I learned everything I know from www.stackoverflow.com and http://wikipedia.org/ and Mom.I can be reached at username@example.com through next Friday.I can be reached at 555-123-4567 through next Friday.I owe $1,000.99 to 123 people for 2+1 reasons.$1.00 equals £0.67 equals €0.91.\",\n",
    "    fix_unicode=True,               # fix various unicode errors\n",
    "    to_ascii=True,                  # transliterate to closest ASCII representation\n",
    "    lower=True,                     # lowercase text\n",
    "    no_line_breaks=False,           # fully strip line breaks as opposed to only normalizing them\n",
    "    no_urls=True,                  # replace all URLs with a special token\n",
    "    no_emails=True,                # replace all email addresses with a special token\n",
    "    no_phone_numbers=True,         # replace all phone numbers with a special token\n",
    "    no_numbers=False,               # replace all numbers with a special token\n",
    "    no_digits=False,                # replace all digits with a special token\n",
    "    no_currency_symbols=True,      # replace all currency symbols with a special token\n",
    "    no_punct=False,                 # fully remove punctuation\n",
    "    replace_with_url=\"<URL>\",\n",
    "    replace_with_email=\"<EMAIL>\",\n",
    "    replace_with_phone_number=\"<PHONE>\",\n",
    "    replace_with_number=\"<NUMBER>\",\n",
    "    replace_with_digit=\"0\",\n",
    "    replace_with_currency_symbol=\"<CUR>\",\n",
    "    lang=\"en\"                       # set to 'de' for German special handling\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/google_api_core-1.16.0-py3.8-nspkg.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "Error processing line 1 of /Users/patsnap/anaconda2/lib/python3.7/site-packages/homebrew.pth:\n",
      "\n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 1280, in find_spec\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 1252, in _get_spec\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 1383, in find_spec\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 95, in _path_isfile\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 87, in _path_is_mode_type\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 81, in _path_stat\n",
      "  RecursionError: maximum recursion depth exceeded while calling a Python object\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 168, in addpackage\n",
      "      exec(line)\n",
      "    File \"<string>\", line 1, in <module>\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 207, in addsitedir\n",
      "      addpackage(sitedir, name, known_paths)\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/site.py\", line 178, in addpackage\n",
      "      import traceback\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/traceback.py\", line 5, in <module>\n",
      "      import linecache\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/linecache.py\", line 11, in <module>\n",
      "      import tokenize\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/tokenize.py\", line 94, in <module>\n",
      "      class TokenInfo(collections.namedtuple('TokenInfo', 'type string start end line')):\n",
      "    File \"/Users/patsnap/anaconda2/lib/python3.7/collections/__init__.py\", line 397, in namedtuple\n",
      "      exec(s, namespace)\n",
      "  RecursionError: maximum recursion depth exceeded during compilation\n",
      "\n",
      "Remainder of file ignored\n",
      "Collecting https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz\n",
      "  Downloading https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz (892.8 MB)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[K     |████████████████████████████████| 892.8 MB 11 kB/s  eta 0:00:012    |█▍                              | 37.5 MB 2.8 MB/s eta 0:05:05     |█▋                              | 45.0 MB 3.2 MB/s eta 0:04:26     |██▍                             | 66.6 MB 3.0 MB/s eta 0:04:37     |███▎                            | 90.3 MB 1.1 MB/s eta 0:12:34     |███▍                            | 94.2 MB 3.0 MB/s eta 0:04:28     |███▊                            | 102.8 MB 802 kB/s eta 0:16:25     |████                            | 112.8 MB 4.3 MB/s eta 0:03:01     |████████▏                       | 229.1 MB 1.3 MB/s eta 0:08:13     |████████▎                       | 231.5 MB 2.8 MB/s eta 0:03:55     |████████▊                       | 242.0 MB 1.5 MB/s eta 0:07:21     |█████████▌                      | 265.2 MB 1.6 MB/s eta 0:06:43     |██████████▊                     | 297.6 MB 2.7 MB/s eta 0:03:44     |██████████▉                     | 301.9 MB 883 kB/s eta 0:11:09     |███████████                     | 305.1 MB 5.0 MB/s eta 0:01:58     |███████████▎                    | 313.8 MB 2.3 MB/s eta 0:04:07     |████████████▏                   | 339.2 MB 1.1 MB/s eta 0:08:34     |█████████████                   | 360.3 MB 360 kB/s eta 0:24:37     |█████████████                   | 360.9 MB 350 kB/s eta 0:25:17     |████████████████▎               | 452.7 MB 686 kB/s eta 0:10:41     |██████████████████              | 500.8 MB 272 kB/s eta 0:23:58     |██████████████████▏             | 506.4 MB 934 kB/s eta 0:06:54     |██████████████████████▏         | 619.8 MB 1.5 MB/s eta 0:03:08     |███████████████████████▍        | 651.3 MB 343 kB/s eta 0:11:43     |████████████████████████        | 668.8 MB 1.3 MB/s eta 0:02:47     |████████████████████████▉       | 693.0 MB 1.0 MB/s eta 0:03:18\n",
      "\u001b[?25hCollecting spacy>=2.3.2\n",
      "  Downloading spacy-2.3.2-cp37-cp37m-macosx_10_9_x86_64.whl (10.0 MB)\n",
      "\u001b[K     |████████████████████████████████| 10.0 MB 10.3 MB/s eta 0:00:01\n",
      "\u001b[?25hRequirement already satisfied: wasabi<1.1.0,>=0.4.0 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (0.4.0)\n",
      "Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (1.0.0)\n",
      "Requirement already satisfied: plac<1.2.0,>=0.9.6 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (0.9.6)\n",
      "Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (2.22.0)\n",
      "Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (1.0.2)\n",
      "Requirement already satisfied: blis<0.5.0,>=0.4.0 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (0.4.1)\n",
      "Requirement already satisfied: thinc==7.4.1 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (7.4.1)\n",
      "Requirement already satisfied: setuptools in /Users/patsnap/.local/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (46.3.0)\n",
      "Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (2.0.2)\n",
      "Requirement already satisfied: numpy>=1.15.0 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (1.18.4)\n",
      "Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (4.41.1)\n",
      "Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (1.0.2)\n",
      "Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from spacy>=2.3.2->en-core-med7-lg==0.0.3) (3.0.2)\n",
      "Requirement already satisfied: importlib-metadata>=0.20; python_version < \"3.8\" in /Users/patsnap/.local/lib/python3.7/site-packages (from catalogue<1.1.0,>=0.0.7->spacy>=2.3.2->en-core-med7-lg==0.0.3) (1.6.0)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.3.2->en-core-med7-lg==0.0.3) (1.24.2)\n",
      "Requirement already satisfied: idna<2.9,>=2.5 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.3.2->en-core-med7-lg==0.0.3) (2.8)\n",
      "Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.3.2->en-core-med7-lg==0.0.3) (3.0.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/patsnap/anaconda2/lib/python3.7/site-packages (from requests<3.0.0,>=2.13.0->spacy>=2.3.2->en-core-med7-lg==0.0.3) (2019.9.11)\n",
      "Requirement already satisfied: zipp>=0.5 in /Users/patsnap/.local/lib/python3.7/site-packages (from importlib-metadata>=0.20; python_version < \"3.8\"->catalogue<1.1.0,>=0.0.7->spacy>=2.3.2->en-core-med7-lg==0.0.3) (3.1.0)\n",
      "Building wheels for collected packages: en-core-med7-lg\n",
      "  Building wheel for en-core-med7-lg (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for en-core-med7-lg: filename=en_core_med7_lg-0.0.3-py3-none-any.whl size=893633388 sha256=ee80fbc7b2ec094e4bd3717ef4c41ab3466bcca1515f07b21a958bdcb6dcaa1d\n",
      "  Stored in directory: /private/var/folders/07/ch803bln2x51cptcxk5bs3gr0000gn/T/pip-ephem-wheel-cache-ec9b2mih/wheels/9d/77/2c/365d93e14dec91a10355606b5f17c76164caa1883295fb6135\n",
      "Successfully built en-core-med7-lg\n",
      "Installing collected packages: spacy, en-core-med7-lg\n",
      "  Attempting uninstall: spacy\n",
      "    Found existing installation: spacy 2.3.1\n",
      "    Uninstalling spacy-2.3.1:\n",
      "      Successfully uninstalled spacy-2.3.1\n",
      "\u001b[31mERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.\n",
      "\n",
      "We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.\n",
      "\n",
      "spacy-transformers 0.5.1 requires spacy<2.3.0,>=2.2.1, but you'll have spacy 2.3.2 which is incompatible.\n",
      "spacy-transformers 0.5.1 requires transformers<2.1.0,>=2.0.0, but you'll have transformers 2.11.0 which is incompatible.\n",
      "pycaret 1.0.0 requires plotly==4.4.1, but you'll have plotly 4.9.0 which is incompatible.\n",
      "pycaret 1.0.0 requires scikit-learn==0.22, but you'll have scikit-learn 0.23.1 which is incompatible.\n",
      "pyate 0.3.9 requires spacy==2.2.4, but you'll have spacy 2.3.2 which is incompatible.\n",
      "nlpre 2.1.1 requires spacy==2.1.0, but you'll have spacy 2.3.2 which is incompatible.\n",
      "medacy 0.2.0 requires scispacy==0.2.2, but you'll have scispacy 0.2.5 which is incompatible.\n",
      "medacy 0.2.0 requires spacy==2.2.0, but you'll have spacy 2.3.2 which is incompatible.\n",
      "medacy 0.2.0 requires torch==1.2.0, but you'll have torch 1.4.0 which is incompatible.\n",
      "medacy 0.2.0 requires transformers==2.3.0, but you'll have transformers 2.11.0 which is incompatible.\u001b[0m\n",
      "Successfully installed en-core-med7-lg-0.0.3 spacy-2.3.2\n",
      "\u001b[33mWARNING: You are using pip version 20.2; however, version 20.2.1 is available.\n",
      "You should consider upgrading via the '/Users/patsnap/anaconda2/bin/python -m pip install --upgrade pip' command.\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install https://med7.s3.eu-west-2.amazonaws.com/en_core_med7_lg.tar.gz"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "import spacy\n",
    "\n",
    "med7 = spacy.load(\"en_core_med7_lg\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# create distinct colours for labels\n",
    "col_dict = {}\n",
    "seven_colours = ['#e6194B', '#3cb44b', '#ffe119', '#ffd8b1', '#f58231', '#f032e6', '#42d4f4']\n",
    "for label, colour in zip(med7.pipe_labels['ner'], seven_colours):\n",
    "    col_dict[label] = colour\n",
    "\n",
    "options = {'ents': med7.pipe_labels['ner'], 'colors':col_dict}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "text = 'A patient was prescribed Magnesium hydroxide 400mg/5ml suspension PO of total 30ml bid for the next 5 days.'\n",
    "doc = med7(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<span class=\"tex2jax_ignore\"><div class=\"entities\" style=\"line-height: 2.5; direction: ltr\">A patient was prescribed \n",
       "<mark class=\"entity\" style=\"background: #3cb44b; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
       "    Magnesium hydroxide\n",
       "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem\">DRUG</span>\n",
       "</mark>\n",
       " \n",
       "<mark class=\"entity\" style=\"background: #e6194B; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
       "    400mg/5ml\n",
       "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem\">DOSAGE</span>\n",
       "</mark>\n",
       " \n",
       "<mark class=\"entity\" style=\"background: #ffd8b1; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
       "    suspension\n",
       "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem\">FORM</span>\n",
       "</mark>\n",
       " \n",
       "<mark class=\"entity\" style=\"background: #f032e6; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
       "    PO\n",
       "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem\">ROUTE</span>\n",
       "</mark>\n",
       " of total \n",
       "<mark class=\"entity\" style=\"background: #e6194B; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
       "    30ml\n",
       "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem\">DOSAGE</span>\n",
       "</mark>\n",
       " \n",
       "<mark class=\"entity\" style=\"background: #f58231; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
       "    bid\n",
       "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem\">FREQUENCY</span>\n",
       "</mark>\n",
       " \n",
       "<mark class=\"entity\" style=\"background: #ffe119; padding: 0.45em 0.6em; margin: 0 0.25em; line-height: 1; border-radius: 0.35em;\">\n",
       "    for the next 5 days\n",
       "    <span style=\"font-size: 0.8em; font-weight: bold; line-height: 1; border-radius: 0.35em; text-transform: uppercase; vertical-align: middle; margin-left: 0.5rem\">DURATION</span>\n",
       "</mark>\n",
       ".</div></span>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": [
       "[('Magnesium hydroxide', 'DRUG'),\n",
       " ('400mg/5ml', 'DOSAGE'),\n",
       " ('suspension', 'FORM'),\n",
       " ('PO', 'ROUTE'),\n",
       " ('30ml', 'DOSAGE'),\n",
       " ('bid', 'FREQUENCY'),\n",
       " ('for the next 5 days', 'DURATION')]"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "spacy.displacy.render(doc, style='ent', jupyter=True, options=options)\n",
    "\n",
    "[(ent.text, ent.label_) for ent in doc.ents]\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
